server:
  port: 8090
spring:
  application:
    name: zipkinclient
  # sleuth.web.enable 设置启用请求跟踪
  # sleuth.sampler.probability 设置采样比例, 默认1.0
  sleuth:
    web:
      enabled: true
    sampler:
      probability: 1.0
  # zipkin server 地址
  zipkin:
    base-url: http://localhost:9090/
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
